network:
  externalHost: 207.188.6.92
  port: 22920
  externalPort: 22920
  bootstrapNodes:
    - /dns4/bootnode-0.mainnet.iotex.one/tcp/4689/p2p/12D3KooWPfQDF8ASjd4r7jS9e7F1wn6zod7Mf4ERr8etoY6ctQp5
    - /dns4/bootnode-1.mainnet.iotex.one/tcp/4689/p2p/12D3KooWN4TQ1CWRA7yvJdQCdti1qARLXXu2UEHJfycn3XbnAnRh
    - /dns4/bootnode-2.mainnet.iotex.one/tcp/4689/p2p/12D3KooWSiktocuUke16bPoW9zrLawEBaEc1UriaPRwm82xbr2BQ
    - /dns4/bootnode-3.mainnet.iotex.one/tcp/4689/p2p/12D3KooWEsmwaorbZX3HRCnhkMPjMAHzwu3om1pdGrtVm2QaM35n
    - /dns4/bootnode-4.mainnet.iotex.one/tcp/4689/p2p/12D3KooWHRcgNim4Nau73EEu7aKJZRZPZ21vQ7BE3fG6vENXkduB
    - /dns4/bootnode-5.mainnet.iotex.one/tcp/4689/p2p/12D3KooWGeHkVDQQFxXpTX1WpPhuuuWYTxPYDUTmaLWWSYx5rmUY

chain:
  # If you are a delegate, make sure producerPrivKey is the key for the operator address you have registered.
  # producerPrivKey: SET YOUR PRIVATE KEY HERE (e.g., 96f0aa5e8523d6a28dc35c927274be4e931e74eaa720b418735debfcbfe712b8)
  chainDBPath: "/home/ansible/nodes/iotex_mainnet_full_2/data/chain.db"
  trieDBPath: "/home/ansible/nodes/iotex_mainnet_full_2/data/trie.db"
  trieDBPatchFile: "/home/ansible/nodes/iotex_mainnet_full_2/data/trie.db.patch"
  indexDBPath: "/home/ansible/nodes/iotex_mainnet_full_2/data/index.db"
  bloomfilterIndexDBPath: "/home/ansible/nodes/iotex_mainnet_full_2/data/bloomfilter.index.db"
  candidateIndexDBPath: "/home/ansible/nodes/iotex_mainnet_full_2/data/candidate.index.db"
  stakingIndexDBPath: "/home/ansible/nodes/iotex_mainnet_full_2/data/staking.index.db"
  maxCacheSize: 1000
  committee:
    gravityChainAPIs:
      # please change the infura key to your key (e.g., https://mainnet.infura.io/v3/YOUR_KEY)
      - https://rpc.ankr.com/eth
    numOfRetries: 20
    paginationSize: 255
    cacheSize: 1000
  gravityChainDB:
    dbPath: "/home/ansible/nodes/iotex_mainnet_full_2/data/poll.db"
    numRetries: 8

actPool:
  minGasPrice: "1000000000000"

api:
  gasStation:
    defaultGas: 1000000000000
  port: 22923
  web3port: 22921
  webSocketPort: 22922

system:
  httpStatsPort: 9019
  httpAdminPort: 8081

consensus:
  scheme: ROLLDPOS
  rollDPoS:
    fsm:
      unmatchedEventTTL: 3s
      unmatchedEventInterval: 100ms
      acceptBlockTTL: 4s
      acceptProposalEndorsementTTL: 2s
      acceptLockEndorsementTTL: 2s
    delay: 10s
    consensusDBPath: "/home/ansible/nodes/iotex_mainnet_full_2/data/consensus.db"

blockSync:
  interval: 10s
  bufferSize: 400
  maxRepeat: 3
  repeatDecayStep: 3

log:
  zap:
    level: info
    encoding: json
    disableStacktrace: true
    outputPaths: ["stderr", "stdout"]
    errorOutputPaths: ["stderr"]
  stderrRedirectFile: /home/ansible/nodes/iotex_mainnet_full_2/log/s.log
  stdLogRedirect: true
